<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>42 Practice Exercise</title>
</head>

<body>
  <h1>Practice Exercise on Promises, Callback and try..catch block</h1>
  <ol>
    <li>Write a program to load a JS File in a browser using Promises. Use .then() to display an alert when the load is
      complete.</li>
    <li>Write the same program from previous question and use async/await syntax.</li>
    <li>Create a promise which rejects after 3 seconds. Use an async/await to get its value. Use a try catch to handle
      its error.</li>
    <li>Write a program using Promise.all() inside an async/await to await 3 promises. Compare its results with the case
      where we await these promises one by one.</li>
  </ol>

  <script>
    // 1. Solution 
    const loadScript = async (src='') =>{
      return new Promise((resolve,reject)=>{
        const scriptTag = document.createElement("script");
        scriptTag.src = src;
        scriptTag.crossOrigin = "anonymous";
        scriptTag.onload = function(){
          resolve({msg: "script is attached to head successfully.", domElement: scriptTag});
        };
        scriptTag.onerror = function(e){
          reject({type: "InvalidUrlError", message: "There is a problem in script url!"});
        }
        document.head.appendChild(scriptTag);
      });
    }

    const srcUrl = "https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/js/bootstrap.min.js";

    loadScript(srcUrl)
    .then(res => {
      console.warn(res.msg);
      console.log(res.domElement);
    }).catch(e => {
      console.error(e.type)
      console.error(e.message)
    });

    
    // 2. Solution
    async function callScript(){
      try {
        const response = await loadScript(srcUrl);
        console.clear();
        console.log(response.msg);
        console.log(response.domElement);
      } catch (error) {
        console.error(error.type+" : "+error.message);
      }
    }

    setTimeout(()=>{
      console.clear();
      // callScript();
    },3000);


    // 3. Solution
    const promiseOne = async()=>{
      return new Promise((resolve,reject)=>{
        setTimeout(()=>{
          reject("Yeh Error PromiseOne se aaya hai!");
        },4000);
      });
    }

    async function app(){
      try {
        await promiseOne();
      } catch (error) {
        console.error(error);
      }
    }

    // app();

    // 4. Solution
    const promise1 = async () =>{
      return new Promise((resolve)=>{
        setTimeout(()=> resolve("Hare Krsna"),3000);
      });
    };
    const promise2 = async () =>{
      return new Promise((resolve)=>{
        setTimeout(()=> resolve("Hare Ram"),1000);
      });
    };
    const promise3 = async () =>{
      return new Promise((resolve)=>{
        setTimeout(()=> resolve("Jai Shri Krsna"),2000);
      });
    };

    async function handleAllPromises() {
      try {
        console.time("timer1");
        const a = await promise1();
        console.log(a);
        const b = await promise2();
        console.log(b);
        const c = await promise3();
        console.log(c);
        console.timeEnd("timer1");
      } catch (error) {
        console.error(error);
      }
    }

    async function handleAllPromises_Optimisely() {
      try {
        console.time("timer2");
        const results = await Promise.all([promise1(),promise2(),promise3()]); // it handles all promises parallelly
        console.log(results);
        console.timeEnd("timer2");
      } catch (error) {
        console.error(error);
      }
    }

    (async()=>{
        try {
          await handleAllPromises(); // almost 6 seconds took
          await handleAllPromises_Optimisely(); // almost 3 seconds took 
          // so here Promise.all() make our code more optimised then general promises which was handled using await.
        } catch (error) {
          console.log(error);
        }
    })();
  </script>
</body>

</html>